#!/usr/bin/env bash
# 11-postgres-backup.sh — daily pg_dump of multica's pgvector container.
#
# Multica's postgres lives in the multica-postgres-1 container (started by
# scripts/06-multica-stack.sh). We dump via `docker exec` and store on host.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
source "$SCRIPT_DIR/_lib.sh"
require_root
require_env

USERNAME="${MULTICA_USER:-multica}"
USER_HOME=$(getent passwd "$USERNAME" | cut -d: -f6)
MULTICA_REPO="$USER_HOME/multica"

BACKUP_DIR="${PG_BACKUP_DIR:-/var/backups/multica}"
RETENTION_DAYS="${PG_BACKUP_RETENTION_DAYS:-14}"
PG_USER="${POSTGRES_USER:-multica}"
PG_DB="${POSTGRES_DB:-multica}"

# ---- Backup directory ----
mkdir -p "$BACKUP_DIR"
chown root:root "$BACKUP_DIR"
chmod 750 "$BACKUP_DIR"

# ---- Backup script (called by systemd) ----
BACKUP_SCRIPT=/usr/local/sbin/multica-pg-backup
cat > "$BACKUP_SCRIPT" <<EOF
#!/usr/bin/env bash
# Auto-generated by 11-postgres-backup.sh — do not edit.
set -euo pipefail
TIMESTAMP=\$(date +%Y%m%d-%H%M%S)
BACKUP_FILE="${BACKUP_DIR}/multica-\${TIMESTAMP}.dump"

# Find multica's postgres container (their compose names it 'multica-postgres-1')
PG_CONTAINER=\$(docker ps --filter 'label=com.docker.compose.project=multica' --filter 'label=com.docker.compose.service=postgres' -q | head -1)
if [[ -z "\$PG_CONTAINER" ]]; then
    echo "ERROR: multica postgres container not found"
    exit 1
fi

# pg_dump in custom format via exec
docker exec "\$PG_CONTAINER" pg_dump -Fc -U "${PG_USER}" -d "${PG_DB}" > "\$BACKUP_FILE"
chmod 640 "\$BACKUP_FILE"

# Retention: delete files older than ${RETENTION_DAYS} days
find "${BACKUP_DIR}" -name 'multica-*.dump' -type f -mtime +${RETENTION_DAYS} -delete

echo "Backup complete: \$BACKUP_FILE"
EOF

chmod 750 "$BACKUP_SCRIPT"
log_ok "Installed $BACKUP_SCRIPT"

# ---- systemd service ----
cat > /etc/systemd/system/multica-pg-backup.service <<EOF
[Unit]
Description=Daily PostgreSQL backup for multica DB (via docker exec)
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
ExecStart=$BACKUP_SCRIPT
User=root
Nice=10
IOSchedulingClass=best-effort
IOSchedulingPriority=7
EOF

# ---- systemd timer (daily at 03:30 server time) ----
cat > /etc/systemd/system/multica-pg-backup.timer <<EOF
[Unit]
Description=Daily PostgreSQL backup timer for multica DB

[Timer]
OnCalendar=*-*-* 03:30:00
Persistent=true
RandomizedDelaySec=600

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now multica-pg-backup.timer

log_ok "systemd timer enabled (daily 03:30)"

# ---- Run one backup now to confirm it works ----
log_info "Running one backup now to verify..."
if systemctl start multica-pg-backup.service; then
    sleep 3
    if [[ -n "$(ls -A "$BACKUP_DIR"/multica-*.dump 2>/dev/null)" ]]; then
        latest=$(ls -t "$BACKUP_DIR"/multica-*.dump | head -1)
        size=$(du -h "$latest" | cut -f1)
        log_ok "Initial backup created: $latest ($size)"
    else
        log_warn "Backup ran but no file created. Check journalctl -u multica-pg-backup"
    fi
else
    log_warn "Initial backup run failed; timer is still scheduled"
fi

log_ok "11-postgres-backup complete"
