#!/usr/bin/env bash
# 17-multica-schema-dump.sh — write per-table DDL dumps of the multica
# postgres DB to /srv/agent-context/multica/pg/<table>.md, mirroring the
# /srv/agent-context/pulse/pg/ layout that Pulse Forge ships.
#
# Why (PUL-163 §4): when an agent picks up a multica-flavoured task,
# discovering the schema by reading migrations one-by-one is slow and
# error-prone (PUL-154 hit migration-number collisions because the agent
# didn't have a clean view of "what numbers are already taken"). A flat
# per-table DDL dump gives them an authoritative current snapshot without
# needing live DB access (`pulse_agent_ro` doesn't exist for the multica DB).
#
# The dump runs out-of-band via systemd timer (hourly), reading the schema
# from inside the multica-postgres-1 container so we don't need the host to
# carry a pg_dump binary at a matching server version.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
source "$SCRIPT_DIR/_lib.sh"
require_root

USERNAME="${MULTICA_USER:-multica}"
DUMP_DIR=/srv/agent-context/multica/pg
CONTAINER=multica-postgres-1
DB_USER=multica
DB_NAME=multica

# Bail cleanly if the multica stack isn't up yet — bootstrap step ordering
# could call this before 06-multica-stack.sh on a fresh host.
if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
    log_skip "$CONTAINER not running — skip multica schema dump"
    exit 0
fi

mkdir -p "$DUMP_DIR"
chown -R "$USERNAME":"$USERNAME" /srv/agent-context/multica 2>/dev/null || true
chmod 755 /srv/agent-context/multica "$DUMP_DIR"

# ---- Dump runner ------------------------------------------------------------
# Use a single-quoted heredoc so the runner is written literally — no shell
# expansion, no backtick traps. Paths are constants here so there's no
# parameterization to lose; if they ever need to vary, switch to envsubst
# or a small templater rather than reintroducing $-expansion in the heredoc.
RUNNER=/usr/local/sbin/multica-schema-dump
cat > "$RUNNER" <<'RUNNER_EOF'
#!/usr/bin/env bash
# Generated by 17-multica-schema-dump.sh. Do not edit by hand.
set -euo pipefail

DUMP_DIR=/srv/agent-context/multica/pg
CONTAINER=multica-postgres-1
DB_USER=multica
DB_NAME=multica

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

# Enumerate base tables in the public schema. No -i on docker exec — the
# while-read loop below would otherwise have its stdin drained by pg_dump
# inside the container, ending the loop after the first table.
docker exec "$CONTAINER" psql -At -U "$DB_USER" -d "$DB_NAME" -c \
    "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename" \
    > "$tmpdir/tables.txt"

# Snapshot existing files so we can prune entries for tables that vanished.
mapfile -t current < <(ls "$DUMP_DIR" 2>/dev/null || true)
declare -A keep
keep["README.md"]=1

while IFS= read -r table; do
    [ -z "$table" ] && continue
    out="$DUMP_DIR/$table.md"
    keep["$table.md"]=1
    {
        printf '# `%s`\n\n' "$table"
        printf 'DDL snapshot — regenerated hourly by multica-schema-dump.timer.\n\n'
        printf '```sql\n'
        docker exec "$CONTAINER" pg_dump \
            --schema-only --no-owner --no-privileges \
            -U "$DB_USER" -d "$DB_NAME" \
            -t "public.$table" \
            | grep -vE '^(SET |SELECT pg_catalog|--$)' \
            | awk 'NF || prev; { prev=NF }'
        printf '```\n'
    } > "$out"
done < "$tmpdir/tables.txt"

cat > "$DUMP_DIR/README.md" <<'README'
# multica DB schema (auto-generated)

Per-table DDL dumps of the `multica` database on `multica-postgres-1`,
regenerated hourly by `multica-schema-dump.timer`.

Use these to look up table shape without needing live DB access. For the
authoritative source, read migrations under
`/srv/agent-worktrees/<task>/server/migrations/` (or the multica bare clone).
README

# Prune dump files for tables that no longer exist.
for f in "${current[@]}"; do
    [ -n "${keep[$f]:-}" ] && continue
    rm -f "$DUMP_DIR/$f"
done
RUNNER_EOF
chmod 0755 "$RUNNER"

# Initial run so the directory has content immediately, not after the first
# timer tick.
log_info "Dumping multica schema (initial run)..."
"$RUNNER"
chown -R "$USERNAME":"$USERNAME" "$DUMP_DIR"
n_tables=$(ls "$DUMP_DIR"/*.md 2>/dev/null | grep -v README.md | wc -l)
log_ok "wrote $n_tables table dump(s) to $DUMP_DIR"

# ---- systemd timer ----------------------------------------------------------
UNIT_NAME=multica-schema-dump
SERVICE=/etc/systemd/system/${UNIT_NAME}.service
TIMER=/etc/systemd/system/${UNIT_NAME}.timer

cat > "$SERVICE" <<EOF
[Unit]
Description=Hourly per-table DDL dump of the multica postgres DB
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
ExecStart=$RUNNER
EOF

cat > "$TIMER" <<EOF
[Unit]
Description=Hourly multica schema dump

[Timer]
OnBootSec=10min
OnUnitActiveSec=1h
Persistent=true

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now "${UNIT_NAME}.timer" >/dev/null
log_ok "${UNIT_NAME}.timer enabled (hourly)"
